---
- name: Install Jenkins with JDK 21
  hosts: server1
  become: true
  tasks:
    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Remove old broken Jenkins list
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Download Jenkins 2026 GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository with signed-by
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins
        update_cache: yes

    - name: Install JDK 21
      apt:
        name: openjdk-21-jre
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
